export const FETCH_ARTICLE_LIST = 'FETCH_ARTICLE_LIST';
export const RECEIVE_ARTICLE_LIST = 'RECEIVE_ARTICLE_LIST';
export const FETCH_TYPE_LIST = 'FETCH_TYPE_LIST';
export const RECEIVE_TYPE_LIST = 'RECEIVE_TYPE_LIST';
export const RECEIVE_ARTICLE_LIST_MORE = 'RECEIVE_ARTICLE_LIST_MORE';

export const RECEIVE_BEAUTY_LIST = 'RECEIVE_BEAUTY_LIST';
//http://gank.io/api/data/iOS/20/2

// 圈子列表
export const FETCH_CIRCLE_LIST = 'FETCH_CIRCLE_LIST';
export const RECEIVE_CIRCLE_LIST = 'RECEIVE_CIRCLE_LIST';
export const RECEIVE_CIRCLE_LIST_MORE = 'RECEIVE_CIRCLE_LIST_MORE';

// 圈子帖子详情
export const RECEIVE_CIRCLE_POST_INFO = 'RECEIVE_CIRCLE_POST_INFO';
// 收藏返回
export const RECEIVE_CIRCLE_POST_COLLECTION = 'RECEIVE_CIRCLE_POST_COLLECTION';
// 点赞返回
export const RECEIVE_CIRCLE_POST_PRAISE = 'RECEIVE_CIRCLE_POST_PRAISE';

// 登录返回
export const RECEIVE_LOGIN = 'RECEIVE_LOGIN';
